# Generated by Django 5.0.7 on 2024-08-05 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MotiveBypass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motiv', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipStatie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_statie', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tipuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transportatori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=255)),
                ('tip_statie', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='app.tipstatie')),
            ],
        ),
        migrations.CreateModel(
            name='Statie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=255)),
                ('cod_statie', models.CharField(blank=True, max_length=255, null=True)),
                ('info_statie', models.TextField(blank=True, null=True)),
                ('tip_statie', models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='app.tipstatie')),
            ],
        ),
        migrations.CreateModel(
            name='Particular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=255)),
                ('tip_statie', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app.tipstatie')),
            ],
        ),
        migrations.CreateModel(
            name='Depozit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=255)),
                ('tip_statie', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='app.tipstatie')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=255)),
                ('tip_statie', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.tipstatie')),
            ],
        ),
        migrations.CreateModel(
            name='Soferi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=255)),
                ('companie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.transportatori')),
            ],
        ),
        migrations.CreateModel(
            name='Cisterne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_cisterna', models.CharField(max_length=255, unique=True)),
                ('companie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.transportatori')),
            ],
        ),
        migrations.CreateModel(
            name='Bypass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observatii', models.CharField(max_length=49)),
                ('cisterna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cisterne')),
                ('motiv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.motivebypass')),
                ('sofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.soferi')),
                ('tip_statie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipstatie')),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipuri')),
                ('transportator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.transportatori')),
            ],
        ),
    ]
