# Generated by Django 5.0.7 on 2024-08-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bypass_utilizator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bypass',
            name='observatii',
            field=models.CharField(max_length=300),
        ),
    ]
